Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Services;
using Models;

namespace Controllers
{
    public class PostsController : Controller
    {
        private BlogData repo;

        public PostsController(BlogData _repo) {
            repo = _repo;
        }

        public ActionResult Index(long userId = -1)
        {
            var vm = repo.Posts;

            if(userId > 0)
                vm = vm.Where(p => p.UserId == userId);

            return View(vm);
        }

        // GET: Post/Details/5
        public ActionResult Details(int id)
        {
            Post p;

            if(repo.PostSet.TryGetValue(id, out p))
                return View(p);
            else
                return new NotFoundResult();
        }
    }
}

Controllers/StatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Services;
using Models;

namespace Controllers
{
    public class StatsController : Controller
    {
        private BlogData repo;

        public StatsController(BlogData _repo) {
            repo = _repo;
        }

        public IActionResult UserPostsCommentsCount(long userId = -1)
        {
            if(userId < 0)
                return View("SelectUser", repo.Users);
            else
                return View(repo.UserPostsCommentsCount(userId));
        }

        public IActionResult ShortUserComments(long userId = -1)
        {
            if(userId < 0)
                return View("SelectUser", repo.Users);
            else
                return View(repo.ShortUserComments(userId));
        }

        public IActionResult CompletedUserTodos(long userId = -1)
        {
            if(userId < 0)
                return View("SelectUser", repo.Users);
            else
                return View(repo.CompletedUserTodos(userId));
        }

        public IActionResult AllUsersTodos()
        {
            return View(repo.AllUsersTodos());
        }

        public IActionResult UserStatistics(long userId = -1)
        {
            if(userId < 0)
                return View("SelectUser", repo.Users);
            else
                return View(repo.UserStatistics(userId));
        }

        public IActionResult PostStatistics(long postId = -1)
        {
            if(postId < 0)
                return View("SelectPost", repo.Posts);
            else
                return View(repo.PostStatistics(postId));
        }
    }
}

Controllers/TodosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Services;
using Models;

namespace Controllers
{
    public class TodosController : Controller
    {
        private BlogData repo;

        public TodosController(BlogData _repo) {
            repo = _repo;
        }

        // GET: Todos
        public ActionResult Index(long userId = -1)
        {
            var ts = repo.Todos;

            if(userId > 0)
                ts = ts.Where(t => t.UserId == userId);

            return View(ts);
        }

        // GET: Todos/Details/5
        public ActionResult Details(int id)
        {
            ToDo res = repo.Todos.Where(t => t.Id == id).FirstOrDefault();
            if(res != null)
                return View(res);
            else
                return new NotFoundResult();
        }
    }
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Services;
using Models;

namespace Controllers
{
    public class UsersController : Controller
    {
        private BlogData repo;

        public UsersController(BlogData _repo) {
            repo = _repo;
        }

        // GET: Users
        public ActionResult Index()
        {
            return View(repo.Users);
        }

        // GET: Users/Details/5
        public ActionResult Details(int id)
        {
            User u;
            if(!repo.UserSet.TryGetValue(id, out u))
                return new NotFoundResult();
                //($"User with id {id} not found");
            
            return View(u);
        }
    }
}

Views/Shared/_App-header-nav.cshtml
<ul class="nav navbar-nav d-md-down-none">
  <li class="nav-item px-3">
    <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
  </li>
  <li class="nav-item px-3">
    <a asp-area="" asp-controller="Home" asp-action="About">About</a>
  </li>
  <li class="nav-item px-3">
    <a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
  </li>
</ul>

Views/Shared/_App-header.cshtml

<header class="app-header navbar">
  <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">
    <img class="navbar-brand-full" src="~/images/brand/logo.svg" width="89" height="25" alt="CoreUI Logo">
    <img class="navbar-brand-minimized" src="~/images/brand/sygnet.svg" width="30" height="30" alt="CoreUI Logo">
  </a>
  <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- APP-HEADER-NAV -->
  @Html.Partial("_App-header-nav")
  <!-- /APP-HEADER-NAV -->

  <div class="nav navbar-nav ml-auto">
    <button class="navbar-toggler aside-menu-toggler d-md-down-none" type="button" data-toggle="aside-menu-lg-show">
      <span class="navbar-toggler-icon"></span>
    </button>
    <button class="navbar-toggler aside-menu-toggler d-lg-none" type="button" data-toggle="aside-menu-show">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>

</header>

Views/Shared/_Breadcrumb-menu.cshtml
<li class="breadcrumb-menu d-md-down-none">
  <div class="btn-group" role="group" aria-label="Button group">
    <a class="btn" href="#">
      <i class="icon-speech"></i>
    </a>
    <a class="btn" asp-area="" asp-controller="CoreUI" asp-action="Index" asp-route-view="">
      <i class="icon-graph"></i> Dashboard
    </a>
    <a class="btn" href="#">
      <i class="icon-settings"></i> Settings
    </a>
  </div>
</li>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--
* CoreUI - Free Bootstrap Admin Template
* @@version v2.0.0
* @@link https://coreui.io
* Copyright (c) 2018 creativeLabs Łukasz Holeczek
* Licensed under MIT (https://coreui.io/license)
*
* Adaptated to ASP.NET Core MVC 2.1 by Miguel Veloso
* http://coderepo.blog
-->

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <meta name="description" content="CoreUI - Open Source Bootstrap Admin Template">
  <meta name="author" content="Łukasz Holeczek">
  <meta name="keyword" content="Bootstrap,Admin,Template,Open,Source,jQuery,CSS,HTML,RWD,Dashboard">
  <title>@ViewData["Title"] - CoBlog</title>

  <!-- Icons-->
  <link href="~/lib/@@coreui/icons/css/coreui-icons.min.css" rel="stylesheet">
  <link href="~/lib/flag-icon-css/css/flag-icon.min.css" rel="stylesheet">
  <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link href="~/lib/simple-line-icons/css/simple-line-icons.css" rel="stylesheet">

  <environment include="Development">
    <!-- Template styles -->
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/vendors/pace-progress/css/pace.css" rel="stylesheet">
    <!-- styles tweaks -->
    <link rel="stylesheet" href="~/css/site.css">
  </environment>

  <environment exclude="Development">
    <!-- Template styles -->
    <link href="~/css/style.min.css" rel="stylesheet" asp-append-version="true">
    <link href="~/vendors/pace-progress/css/pace.min.css" rel="stylesheet" asp-append-version="true">
    <!-- styles tweaks -->
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true">
  </environment>

</head>
<body class="app sidebar-fixed sidebar-lg-show bg-gray-200">

  <div class="app-body">
    <div class="sidebar">

      <!-- SIDEBAR-NAV -->
      @Html.Partial("_Sidebar-nav")
      <!-- /SIDEBAR-NAV -->

      <button class="sidebar-minimizer brand-minimizer" type="button"></button>
    </div>
    <main class="main">

      <!-- VIEW-BREADCRUMBS -->
      @RenderSection("Breadcrumbs", required: false)
      <!-- /VIEW-BREADCRUMBS -->

      <div class="container-fluid">

        <!-- VIEW-STYLES -->
        @RenderSection("Styles", required: false)
        <!-- /VIEW-STYLES -->

        <div class="animated fadeIn">

          <!-- VIEW-CONTENT -->
          @RenderBody()
          <!-- /VIEW-CONTENT -->

        </div>

        <!-- VIEW-MODALS -->
        @RenderSection("Modals", required: false)
        <!-- /VIEW-MODALS -->

      </div>
    </main>

  </div>

  <environment include="Development">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
  </environment>
  <environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
  </environment>

  <script src="~/lib/popper.js/dist/umd/popper.min.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
  <script src="~/lib/pace-progress/pace.min.js"></script>
  <script src="~/lib/perfect-scrollbar/dist/perfect-scrollbar.min.js"></script>
  <script src="~/lib/@@coreui/coreui/dist/js/coreui.min.js"></script>

  <environment include="Development">
    <script src="~/js/site.js" asp-append-version="true"></script>
  </environment>
  <environment exclude="Development">
    <script src="~/js/site.min.js" asp-append-version="true"></script>
  </environment>

  <!-- VIEW-SCRIPTS -->
  @RenderSection("Scripts", required: false)
  <!-- /VIEW-SCRIPTS -->

</body>
</html>

Views/Shared/_Sidebar-nav.cshtml
<nav class="sidebar-nav">
  <ul class="nav">
    <li class="nav-item">
      <a class="nav-link" asp-controller="Home" asp-action="Index">
        <i class="nav-icon icon-speedometer"></i> Dashboard
      </a>
    </li>
    <li class="nav-title">Blog</li>
    <li class="nav-item">
      <a class="nav-link" asp-controller="Posts" asp-action="Index">
        <i class="nav-icon icon-notebook"></i>
        Posts
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" asp-controller="Users" asp-action="Index">
        <i class="nav-icon icon-people"></i>
        Users
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" asp-controller="Todos" asp-action="Index">
        <i class="nav-icon icon-calendar"></i>
        ToDos
      </a>
    </li>

    <li class="nav-title">Stats</li>
        <li class="nav-item">
          <a class="nav-link" asp-controller="Stats" asp-action="UserPostsCommentsCount">
            <i class="nav-icon icon-puzzle"></i>
            Comment counts
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link" asp-controller="Stats" asp-action="ShortUserComments">
            <i class="nav-icon icon-puzzle"></i>
            Short comments
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link" asp-controller="Stats" asp-action="CompletedUserTodos">
            <i class="nav-icon icon-puzzle"></i>
            Completed todos
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link" asp-controller="Stats" asp-action="AllUsersTodos">
            <i class="nav-icon icon-puzzle"></i>
            All users todos
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link" asp-controller="Stats" asp-action="UserStatistics">
            <i class="nav-icon icon-puzzle"></i>
            User query
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link" asp-controller="Stats" asp-action="PostStatistics">
            <i class="nav-icon icon-puzzle"></i>
            Post query
          </a>
        </li>

    </li>
  </ul>
</nav>